version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: tsbridge
    main: ./cmd/tsbridge
    binary: tsbridge
    goos:
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.gitCommit={{.ShortCommit}} -X main.buildDate={{.Date}}
    flags:
      - -trimpath

archives:
  - id: tsbridge
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: [tar.gz, zip]
    files:
      - LICENSE
      - README.md

dockers_v2:
  - id: tsbridge
    images:
      - ghcr.io/jtdowney/tsbridge
    tags:
      - "{{ .Tag }}"
      - "v{{ .Major }}.{{ .Minor }}"
      - latest
      # TODO: Uncomment for 1.0.0 release
      # - "{{ .Major }}"
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.description: Tailscale-based reverse proxy manager
      org.opencontainers.image.url: https://github.com/jtdowney/tsbridge
      org.opencontainers.image.source: https://github.com/jtdowney/tsbridge
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.licenses: MIT

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-SNAPSHOT-{{ .ShortCommit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: jtdowney
    name: tsbridge
  draft: false
  prerelease: auto
  name_template: "{{ .Tag }}"